name: Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier and fix issues
        run: pnpm prettier --write .

      - name: Run ESLint and fix issues
        run: pnpm eslint . --ext .js,.jsx,.ts,.tsx --fix

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Auto-fix issues"
          git push
        if: ${{ steps.lint-and-format.outcome == 'success' }}
